### ISSUE TITLE
Remove the Guttman wiping method

### ISSUE THREAD

**Issue by vatterspun** [yunzhu-li/winaes#1]
I'd like to recommend the removal of the 35-pass method and instead replace it with a 1-pass (zero out and/or pseudorandom), 3, and 7 method pass.  Here's some analysis of why:

https://en.wikipedia.org/wiki/Gutmann_method#Criticism

... additionally as most people have flash media, it can dramatically decrease drive life without doing much for security.

**Comment by yunzhu-li** [comment]
Hi @vatterspun, thank you for your feedback! This project is no longer maintained unfortunately so I'm closing this issue for now.
