### ISSUE TITLE
Feature request: optional *** over password (over-the-shoulder attack)

### ISSUE THREAD

**Issue by vatterspun** [yunzhu-li/winaes#2]
I like the default behavior but I think this would be necessary for some folks before they'd actively use it.

-- Current behavior --

Typing out the password is visible to someone looking over your shoulder and again when prompted after clicking "encrypt".

-- Requested behavior --

Menu option (maybe an added configuration window) to obscure password by asterisks

**Comment by yunzhu-li** [comment]
Closing this, see https://github.com/yunzhu-li/winaes/issues/1#issuecomment-417177786
