### ISSUE TITLE
Feature request: ability to add whole directories for encrypt/decrypt

### ISSUE THREAD

**Issue by vatterspun** [yunzhu-li/winaes#3]
-- Current behavior --

Adding a folder with files in subfolders gives an "encryption failed" error msg in the main window under "status"

-- Requested behavior --

All files added should be encrypted with .aes256 appended to the end of the file.

Decryption should work similarly with any .aes256 files decrypted using the supplied password.

**Comment by yunzhu-li** [comment]
Closing this, see: https://github.com/yunzhu-li/winaes/issues/1#issuecomment-417177786
